from __future__ import annotations

import argparse
from collections import defaultdict
from pathlib import Path

import zhivex_ai


ROOT = Path(__file__).resolve().parents[1]
STUB_PATH = ROOT / "src" / "zhivex_ai" / "__init__.pyi"


def render_public_stub() -> str:
    modules: dict[str, list[str]] = defaultdict(list)
    for export_name, module_name in sorted(zhivex_ai._EXPORTS.items()):
        modules[module_name].append(export_name)

    lines = [
        "# Generated by scripts/generate_public_stub.py. Do not edit by hand.",
        "from __future__ import annotations",
        "",
        "from typing import Any",
        "",
    ]
    for module_name in sorted(modules):
        names = modules[module_name]
        lines.append(f"from .{module_name} import (")
        lines.extend(f"    {name} as {name}," for name in names)
        lines.append(")")
        lines.append("")
    lines.extend(
        [
            "__all__: list[str]",
            "",
            "def __getattr__(name: str) -> Any: ...",
            "def __dir__() -> list[str]: ...",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the typed top-level zhivex_ai public surface.")
    parser.add_argument("--check", action="store_true", help="Fail if the committed stub is stale.")
    args = parser.parse_args()
    expected = render_public_stub()
    if args.check:
        actual = STUB_PATH.read_text("utf-8") if STUB_PATH.exists() else ""
        if actual != expected:
            raise SystemExit(f"{STUB_PATH.relative_to(ROOT)} is stale; run scripts/generate_public_stub.py")
        return 0
    STUB_PATH.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
