from __future__ import annotations

from importlib import import_module

from .embed import embed, embed_many
from .generate_object import generate_object, stream_object
from .generate_text import generate_text, stream_text

_MODULE_EXPORTS = {
    "agent": (
        "Agent",
        "AgentContext",
        "AgentCheckpoint",
        "AgentCheckpointEvent",
        "AgentDelegationFinishEvent",
        "AgentDelegationStartEvent",
        "AgentErrorEvent",
        "AgentEvent",
        "AgentFinishEvent",
        "AgentHandoff",
        "AgentHandoffEvent",
        "AgentHandoffFailedEvent",
        "AgentHandoffRequestedEvent",
        "AgentHandoffResolvedEvent",
        "AgentLiveEvent",
        "AgentMemoryState",
        "AgentRegistry",
        "AgentRunResult",
        "AgentRunStartEvent",
        "AgentSession",
        "AgentSummaryUpdateEvent",
        "AgentTextDeltaEvent",
        "AgentToolApprovalEvent",
        "AgentToolCallEvent",
        "AgentToolResultEvent",
        "AgentTrace",
        "AgentTraceSegment",
        "AgentRuntime",
        "ApprovalDecision",
        "LiveAgentStreamResult",
        "SummaryConfig",
        "ToolRegistry",
        "RunLimits",
        "ToolApprovalRequest",
        "allow_all_approval_policy",
        "create_agent_session",
        "create_mcp_tool_registry",
        "create_in_memory_agent_memory_store",
        "create_in_memory_checkpoint_store",
        "create_postgres_agent_memory_store",
        "create_postgres_checkpoint_store",
        "create_sqlite_agent_memory_store",
        "create_sqlite_checkpoint_store",
        "deny_all_approval_policy",
        "discover_mcp_tools",
        "handoff_to",
        "load_agent_session",
        "mcp_http_server",
        "mcp_stdio_server",
        "permission_allowlist_approval_policy",
        "resume_agent",
        "run_agent",
        "stream_agent",
        "stream_live_agent",
    ),
    "catalog": ("ModelCatalog", "ModelCatalogEntry", "create_model_catalog", "default_model_catalog"),
    "audio": ("generate_speech", "transcribe_audio"),
    "gateway": (
        "GatewayAttempt",
        "GatewayConfig",
        "GatewayError",
        "GatewayImageAttachment",
        "GatewayMessage",
        "GatewayModelTarget",
        "GatewayObjectResponse",
        "GatewayResponse",
        "create_gateway",
    ),
    "middleware": (
        "CircuitBreakerState",
        "create_cached_generate_middleware",
        "create_circuit_breaker_middleware",
        "create_file_generate_cache",
        "create_in_memory_generate_cache",
        "create_telemetry_middleware",
        "wrap_language_model",
    ),
    "grounded_text": ("generate_grounded_text",),
    "embed": ("embed", "embed_many"),
    "errors": (
        "ConfigurationError",
        "ParseError",
        "ProviderHTTPError",
        "UnsupportedFeatureError",
        "ValidationError",
    ),
    "generate_object": ("generate_object", "stream_object"),
    "generate_text": ("generate_text", "stream_text"),
    "messages": (
        "assistant",
        "create_text_message",
        "remote_tool",
        "system",
        "text_part",
        "tool",
        "tool_call_part",
        "tool_result_part",
        "user",
    ),
    "realtime": ("open_websocket_connection",),
    "transport": (
        "HTTPResponse",
        "create_ui_message_json_response",
        "create_ui_message_lines_response",
        "parse_ui_message_request",
        "stream_sse",
        "to_sse_response",
        "to_sse_stream",
        "to_text_stream",
        "to_text_stream_response",
        "to_ui_message_stream_response",
    ),
    "ui": (
        "collect_ui_message",
        "deserialize_ui_message",
        "deserialize_ui_message_chunk",
        "from_ui_message",
        "from_ui_messages",
        "serialize_ui_message",
        "serialize_ui_message_chunk",
        "to_ui_message",
        "to_ui_message_stream",
        "to_ui_messages",
    ),
    "observability": ("OTelAgentObserver", "create_otel_agent_observer"),
    "providers.anthropic": ("create_anthropic",),
    "providers.azure_openai": ("create_azure_openai",),
    "providers.bedrock": ("create_bedrock",),
    "providers.gemini": ("create_gemini",),
    "providers.kimi": ("create_kimi",),
    "providers.ollama": ("create_ollama",),
    "providers.openai": ("create_openai",),
    "providers.openrouter": ("create_openrouter",),
    "providers.qwen": ("create_qwen",),
    "providers.vertex": ("create_vertex",),
    "types": (
        "AudioFrame",
        "AudioInput",
        "ContentPart",
        "EmbedOutput",
        "EmbeddingModel",
        "FinishReason",
        "GenerateGroundedTextOutput",
        "GenerateObjectOutput",
        "GenerateTextOutput",
        "GroundedLanguageModel",
        "GroundingSource",
        "ImagePart",
        "LanguageModel",
        "MCPServerConfig",
        "MCPToolConfig",
        "MessageRole",
        "ModelCapabilities",
        "ModelMessage",
        "RealtimeAudioOutputEvent",
        "RealtimeConnectOptions",
        "RealtimeErrorEvent",
        "RealtimeEvent",
        "RealtimeModel",
        "RealtimeSession",
        "RealtimeSessionConfig",
        "RealtimeSessionEndedEvent",
        "RealtimeSessionStartedEvent",
        "RealtimeTextDeltaEvent",
        "RealtimeTokenResult",
        "RealtimeToolCallEvent",
        "RealtimeToolResultEvent",
        "RealtimeTranscriptEvent",
        "RemoteHTTPToolConfig",
        "ReasoningConfig",
        "SpeechModel",
        "SpeechOutput",
        "StreamEvent",
        "StreamFinishEvent",
        "StreamObjectResult",
        "StreamTextDeltaEvent",
        "StreamTextResult",
        "TextPart",
        "ToolChoiceName",
        "ToolExecutionContext",
        "ToolExecutionOptions",
        "ToolSource",
        "TokenUsage",
        "TranscriptionModel",
        "TranscriptionOutput",
        "ToolCall",
        "ToolDefinition",
        "ToolExecutionError",
        "ToolExecutionResult",
        "UIMessage",
        "UIMessageChunk",
    ),
}

__all__ = [
    "Agent",
    "AgentContext",
    "AgentCheckpoint",
    "AgentCheckpointEvent",
    "AgentDelegationFinishEvent",
    "AgentDelegationStartEvent",
    "AgentErrorEvent",
    "AgentEvent",
    "AgentFinishEvent",
    "AgentHandoff",
    "AgentHandoffEvent",
    "AgentHandoffFailedEvent",
    "AgentHandoffRequestedEvent",
    "AgentHandoffResolvedEvent",
    "AgentLiveEvent",
    "AgentMemoryState",
    "AgentRegistry",
    "AgentRunResult",
    "AgentRunStartEvent",
    "AgentRuntime",
    "LiveAgentStreamResult",
    "AgentSession",
    "AgentSummaryUpdateEvent",
    "AgentTextDeltaEvent",
    "AgentToolApprovalEvent",
    "AgentToolCallEvent",
    "AgentToolResultEvent",
    "AgentTrace",
    "AgentTraceSegment",
    "ApprovalDecision",
    "ConfigurationError",
    "HTTPResponse",
    "AudioFrame",
    "AudioInput",
    "ContentPart",
    "EmbedOutput",
    "EmbeddingModel",
    "FinishReason",
    "GenerateGroundedTextOutput",
    "GatewayAttempt",
    "GatewayConfig",
    "GatewayError",
    "GatewayImageAttachment",
    "GatewayMessage",
    "GatewayModelTarget",
    "GatewayObjectResponse",
    "GatewayResponse",
    "ModelCatalog",
    "ModelCatalogEntry",
    "GenerateObjectOutput",
    "GenerateTextOutput",
    "GroundedLanguageModel",
    "GroundingSource",
    "ImagePart",
    "LanguageModel",
    "MCPServerConfig",
    "MCPToolConfig",
    "MessageRole",
    "ModelCapabilities",
    "ModelMessage",
    "ParseError",
    "ProviderHTTPError",
    "RealtimeAudioOutputEvent",
    "RealtimeConnectOptions",
    "RealtimeErrorEvent",
    "RealtimeEvent",
    "RealtimeModel",
    "RealtimeSession",
    "RealtimeSessionConfig",
    "RealtimeSessionEndedEvent",
    "RealtimeSessionStartedEvent",
    "RealtimeTextDeltaEvent",
    "RealtimeTokenResult",
    "RealtimeToolCallEvent",
    "RealtimeToolResultEvent",
    "RealtimeTranscriptEvent",
    "RemoteHTTPToolConfig",
    "ReasoningConfig",
    "RunLimits",
    "SummaryConfig",
    "CircuitBreakerState",
    "ToolExecutionContext",
    "SpeechModel",
    "SpeechOutput",
    "StreamEvent",
    "StreamFinishEvent",
    "StreamObjectResult",
    "StreamTextDeltaEvent",
    "StreamTextResult",
    "TextPart",
    "ToolChoiceName",
    "ToolExecutionOptions",
    "ToolRegistry",
    "ToolSource",
    "TokenUsage",
    "TranscriptionModel",
    "TranscriptionOutput",
    "ToolCall",
    "ToolDefinition",
    "ToolApprovalRequest",
    "ToolExecutionError",
    "ToolExecutionResult",
    "UIMessage",
    "UIMessageChunk",
    "UnsupportedFeatureError",
    "ValidationError",
    "allow_all_approval_policy",
    "assistant",
    "create_agent_session",
    "create_anthropic",
    "create_azure_openai",
    "create_bedrock",
    "create_cached_generate_middleware",
    "create_circuit_breaker_middleware",
    "create_file_generate_cache",
    "create_gateway",
    "create_gemini",
    "create_in_memory_generate_cache",
    "create_in_memory_agent_memory_store",
    "create_in_memory_checkpoint_store",
    "create_mcp_tool_registry",
    "create_postgres_agent_memory_store",
    "create_postgres_checkpoint_store",
    "create_kimi",
    "create_model_catalog",
    "create_otel_agent_observer",
    "create_ollama",
    "create_openai",
    "create_openrouter",
    "create_qwen",
    "create_sqlite_agent_memory_store",
    "create_sqlite_checkpoint_store",
    "create_telemetry_middleware",
    "create_vertex",
    "create_ui_message_json_response",
    "create_ui_message_lines_response",
    "create_text_message",
    "collect_ui_message",
    "default_model_catalog",
    "deny_all_approval_policy",
    "deserialize_ui_message",
    "deserialize_ui_message_chunk",
    "discover_mcp_tools",
    "embed",
    "embed_many",
    "from_ui_message",
    "from_ui_messages",
    "generate_grounded_text",
    "generate_object",
    "generate_speech",
    "generate_text",
    "handoff_to",
    "parse_ui_message_request",
    "serialize_ui_message",
    "serialize_ui_message_chunk",
    "load_agent_session",
    "mcp_http_server",
    "mcp_stdio_server",
    "OTelAgentObserver",
    "permission_allowlist_approval_policy",
    "remote_tool",
    "resume_agent",
    "run_agent",
    "open_websocket_connection",
    "stream_sse",
    "stream_object",
    "stream_agent",
    "stream_live_agent",
    "stream_text",
    "system",
    "text_part",
    "to_sse_response",
    "to_sse_stream",
    "to_text_stream",
    "to_text_stream_response",
    "to_ui_message",
    "to_ui_message_stream",
    "to_ui_message_stream_response",
    "to_ui_messages",
    "tool",
    "tool_call_part",
    "tool_result_part",
    "transcribe_audio",
    "user",
    "wrap_language_model",
]

_EXPORTS = {
    export_name: module_name
    for module_name, export_names in _MODULE_EXPORTS.items()
    for export_name in export_names
}

if set(__all__) != set(_EXPORTS):
    missing = sorted(set(__all__) - set(_EXPORTS))
    extra = sorted(set(_EXPORTS) - set(__all__))
    raise RuntimeError(f"zhivex_ai export map is out of sync. missing={missing} extra={extra}")


def __getattr__(name: str):
    module_name = _EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(f".{module_name}", __name__)
    value = getattr(module, name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
