from __future__ import annotations

from dataclasses import dataclass
from typing import Literal, Mapping

ApiStabilityLevel = Literal["stable", "beta", "experimental"]


@dataclass(frozen=True)
class ApiStabilityEntry:
    name: str
    level: ApiStabilityLevel
    category: str
    notes: str = ""


STABLE_EXPORTS = frozenset(
    (
        "Agent",
        "AgentHandoff",
        "AgentRegistry",
        "AgentReplayEvent",
        "AgentReplayResult",
        "AgentRuntime",
        "AgentSession",
        "AgentChildRun",
        "AgentRunResult",
        "AgentEventDeliveryError",
        "AgentRunCancelled",
        "AgentRunSnapshot",
        "AgentRunState",
        "AgentRunStatus",
        "AgentRunStep",
        "AgentRunStore",
        "AgentRunTreeCancellationResult",
        "AgentStreamResult",
        "AgentSkillActivatedEvent",
        "AgentSkillSkippedEvent",
        "AgentToolApprovalEvent",
        "ApprovalDecision",
        "ConfigurationError",
        "GatewayAttempt",
        "GatewayConfig",
        "GatewayError",
        "GatewayImageAttachment",
        "GatewayMessage",
        "GatewayModelTarget",
        "GatewayObjectResponse",
        "GatewayResponse",
        "HTTPResponse",
        "PendingApproval",
        "ProviderHTTPError",
        "ToolExecutionOutcomeUnknown",
        "PostgresAgentRunStore",
        "SkillDefinition",
        "SkillDependency",
        "SkillRegistry",
        "ToolApprovalRequest",
        "ToolDefinition",
        "ToolExecutionContext",
        "ToolExecutionError",
        "ToolExecutionOptions",
        "ToolExecutionResult",
        "ToolRegistry",
        "ToolSet",
        "UnsupportedFeatureError",
        "ValidationError",
        "agent_run_state_from_json",
        "agent_run_state_to_json",
        "cancel_agent_run",
        "cancel_agent_run_tree",
        "clear_agent_session_skills",
        "create_agent_session",
        "create_agent_run_snapshot",
        "create_anthropic",
        "create_azure_openai",
        "create_gateway",
        "create_gemini",
        "create_kimi",
        "create_mcp_tool_registry",
        "create_openai",
        "create_postgres_agent_memory_store",
        "create_postgres_agent_run_store",
        "create_postgres_checkpoint_store",
        "create_qwen",
        "create_vertex",
        "create_vllm",
        "deserialize_agent_run_state",
        "discover_mcp_tools",
        "discover_skills",
        "embed",
        "embed_content",
        "embed_content_many",
        "embed_many",
        "generate_grounded_text",
        "generate_object",
        "generate_text",
        "get_agent_session_skills",
        "get_pending_agent_approvals",
        "handoff_to",
        "load_agent_session",
        "load_skill",
        "mcp_http_server",
        "mcp_stdio_server",
        "replay_agent_run",
        "resume_agent",
        "resume_agent_run",
        "run_agent",
        "serialize_agent_run_state",
        "set_agent_session_skills",
        "skill",
        "stream_agent",
        "stream_object",
        "stream_sse",
        "stream_text",
        "tool",
        "to_sse_response",
        "to_sse_stream",
        "to_text_stream",
        "to_text_stream_response",
        "to_ui_message_stream_response",
    )
)

EXPERIMENTAL_EXPORTS = frozenset(
    (
        "AgentLiveEvent",
        "LiveAgentStreamResult",
        "RealtimeAudioOutputEvent",
        "RealtimeConnectOptions",
        "RealtimeErrorEvent",
        "RealtimeEvent",
        "RealtimeModel",
        "RealtimeResponseCompletedEvent",
        "RealtimeSession",
        "RealtimeSessionConfig",
        "RealtimeSessionEndedEvent",
        "RealtimeSessionStartedEvent",
        "RealtimeTextDeltaEvent",
        "RealtimeTokenResult",
        "RealtimeToolCallEvent",
        "RealtimeToolResultEvent",
        "RealtimeTranscriptEvent",
        "open_websocket_connection",
        "openai_local_shell_tool",
        "openai_shell_environment",
        "openai_shell_tool",
        "stream_live_agent",
    )
)

BETA_EXPORTS = frozenset(
    (
        "AGENT_RUN_STATE_SCHEMA_VERSION",
        "AgentCapabilities",
        "AgentCheckpoint",
        "AgentCheckpointEvent",
        "AgentContext",
        "AgentDelegationFinishEvent",
        "AgentDelegationStartEvent",
        "AgentErrorEvent",
        "AgentEvaluationCase",
        "AgentEvaluationCaseResult",
        "AgentEvaluationExpectations",
        "AgentEvaluationFixture",
        "AgentEvaluationJudgeResult",
        "AgentEvaluationReport",
        "AgentEvaluationResult",
        "AgentEvent",
        "AgentFinishEvent",
        "AgentGroupMember",
        "AgentGroupMemberResult",
        "AgentGroupRunResult",
        "AgentGuardrailEvent",
        "AgentHandoffEvent",
        "AgentHandoffFailedEvent",
        "AgentHandoffRequestedEvent",
        "AgentHandoffResolvedEvent",
        "AgentMemoryState",
        "AgentRunStartEvent",
        "AgentRunTreeNode",
        "AgentRunTreeSnapshot",
        "AgentSkillArtifactCreatedEvent",
        "AgentSkillDependencyCheckEvent",
        "AgentSkillExecutionFinishEvent",
        "AgentSkillExecutionStartEvent",
        "AgentSkillResolvedEvent",
        "AgentSummaryUpdateEvent",
        "AgentSupportTier",
        "AgentTextDeltaEvent",
        "AgentToolCallEvent",
        "AgentToolResultEvent",
        "AgentTrace",
        "AgentTraceArtifact",
        "AgentTraceCollector",
        "AgentTraceSegment",
        "AgentTraceStep",
        "AgentTraceSummary",
        "AnyToolDefinition",
        "ApprovalPolicyOptions",
        "ApprovalPolicyPreset",
        "AudioFrame",
        "AudioInput",
        "AzureOpenAIMcpApprovalRequest",
        "AzureOpenAIMcpApprovalResponse",
        "AzureOpenAIMcpCall",
        "AzureOpenAIMcpListTools",
        "AzureOpenAIProviderData",
        "AzureOpenAIResponseReference",
        "BatchesClient",
        "BudgetGuard",
        "CachedContent",
        "CachedContentListResult",
        "CachedContentsClient",
        "CircuitBreakerState",
        "ContainersClient",
        "ContentPart",
        "ConversationsClient",
        "CostEstimate",
        "CountTokensClient",
        "CountTokensResult",
        "EmbedOutput",
        "EmbeddingContent",
        "EmbeddingModel",
        "EmbeddingPart",
        "FilePart",
        "FileSearchBatch",
        "FileSearchDocument",
        "FileSearchDocumentListResult",
        "FileSearchOperation",
        "FileSearchSearchResult",
        "FileSearchStore",
        "FileSearchStoreListResult",
        "FileSearchStoresClient",
        "FilesClient",
        "FinishReason",
        "GenerateGroundedTextOutput",
        "GenerateObjectOutput",
        "GenerateTextOutput",
        "GeneratedMedia",
        "GroundedLanguageModel",
        "GroundingSource",
        "GuardrailResult",
        "GuardrailTripwireTriggered",
        "HierarchicalAgentTrace",
        "HierarchicalAgentTraceNode",
        "HostedToolClass",
        "HostedToolDefinition",
        "ImagePart",
        "ImagesClient",
        "ImagesResult",
        "InMemoryAgentRunStore",
        "InputGuardrail",
        "InputGuardrailRequest",
        "InstalledSkill",
        "InteractionsClient",
        "KIMI_OFFICIAL_TOOL_URIS",
        "KimiFormulaClient",
        "LanguageModel",
        "LoopAgent",
        "MCPServerConfig",
        "MCPToolConfig",
        "MediaClient",
        "MediaResult",
        "MessageRole",
        "ModelCapabilities",
        "ModelCatalog",
        "ModelCatalogEntry",
        "ModelMessage",
        "ModerationsClient",
        "NativeSupport",
        "OTelAgentObserver",
        "OpenAIMcpApprovalRequest",
        "OpenAIMcpApprovalResponse",
        "OpenAIMcpCall",
        "OpenAIMcpListTools",
        "OpenAIProviderData",
        "OpenAIResponseReference",
        "OutputGuardrail",
        "OutputGuardrailRequest",
        "ParallelAgent",
        "ParseError",
        "PortableDocument",
        "PortableGroundingConfig",
        "PortableProviderNamespace",
        "PortableProviderTier",
        "PortableRetrievalConfig",
        "PortableSpeechConfig",
        "PortableSupport",
        "PortableTranscriptionConfig",
        "ProviderBundle",
        "ProviderDataPart",
        "ProviderFile",
        "ProviderImage",
        "ProviderSupportRow",
        "ProviderUpload",
        "ProviderUploadPart",
        "ReasoningConfig",
        "RedactionPolicy",
        "RedactionRule",
        "RemoteHTTPToolConfig",
        "ResponsesClient",
        "RunLimits",
        "SQLiteAgentRunStore",
        "SafetyPolicy",
        "SafetyPolicyPreset",
        "SequentialAgent",
        "SkillArtifact",
        "SkillEntrypoint",
        "SkillPackageManifest",
        "SkillPermissions",
        "SkillRegistryIndex",
        "SkillRunResult",
        "SkillsClient",
        "SpeechModel",
        "SpeechOutput",
        "StreamEvent",
        "StreamFinishEvent",
        "StreamObjectResult",
        "StreamProviderDataEvent",
        "StreamTextDeltaEvent",
        "StreamTextResult",
        "SummaryConfig",
        "TextPart",
        "TokenCountDetail",
        "TokenPricing",
        "TokenUsage",
        "ToolCall",
        "ToolChoiceName",
        "ToolSource",
        "TranscriptionModel",
        "TranscriptionOutput",
        "UIMessage",
        "UIMessageChunk",
        "UIMessageProviderDataChunk",
        "UIMessageToolApprovalChunk",
        "UploadsClient",
        "VideoOperation",
        "VideoResult",
        "VideosClient",
        "WorkflowAgent",
        "WorkflowErrorPolicy",
        "WorkflowRunResult",
        "WorkflowState",
        "WorkflowStep",
        "WorkflowStepResult",
        "WorkflowStopCondition",
        "WorkflowTraceEvent",
        "agent_child_run_from_state",
        "allow_all_approval_policy",
        "anthropic_code_execution_tool",
        "anthropic_mcp_server",
        "anthropic_web_fetch_tool",
        "anthropic_web_search_tool",
        "apply_safety_policy_to_agent",
        "assistant",
        "azure_openai_computer_use_tool",
        "azure_openai_file_search_tool",
        "azure_openai_mcp_approval_response",
        "azure_openai_mcp_tool",
        "azure_openai_response_reference",
        "azure_openai_web_search_tool",
        "build_provider_support_rows",
        "collect_ui_message",
        "create_agent_evaluation_fixture",
        "create_agent_evaluation_report",
        "create_agent_run_tree_snapshot",
        "create_agent_trace_artifact",
        "create_agent_trace_collector",
        "create_approval_policy",
        "create_bedrock",
        "create_budget_guard",
        "create_cached_generate_middleware",
        "create_circuit_breaker_middleware",
        "create_file_generate_cache",
        "create_hierarchical_agent_trace",
        "create_in_memory_agent_memory_store",
        "create_in_memory_agent_run_store",
        "create_in_memory_checkpoint_store",
        "create_in_memory_generate_cache",
        "create_mock_language_model",
        "create_mock_tool",
        "create_model_catalog",
        "create_ollama",
        "create_openrouter",
        "create_otel_agent_observer",
        "create_redaction_policy",
        "create_safety_policy",
        "create_sqlite_agent_memory_store",
        "create_sqlite_agent_run_store",
        "create_sqlite_checkpoint_store",
        "create_subagent_tool",
        "create_telemetry_middleware",
        "create_text_message",
        "create_ui_message_json_response",
        "create_ui_message_lines_response",
        "default_model_catalog",
        "deny_all_approval_policy",
        "fail_agent_run_resume_claim",
        "deserialize_ui_message",
        "deserialize_ui_message_chunk",
        "estimate_agent_run_cost",
        "estimate_token_cost",
        "from_ui_message",
        "from_ui_messages",
        "gemini_code_execution_tool",
        "gemini_computer_use_tool",
        "gemini_file_search_tool",
        "gemini_google_maps_tool",
        "gemini_google_search_tool",
        "gemini_hosted_tool",
        "gemini_url_context_tool",
        "generate_speech",
        "get_agent_capabilities",
        "get_agent_support_tier",
        "get_azure_openai_response_id",
        "get_azure_openai_response_reference",
        "get_hosted_tool_class",
        "get_last_provider_data_part",
        "get_openai_response_id",
        "get_openai_response_reference",
        "get_provider_data_parts",
        "hosted_tool",
        "install_skill",
        "is_callable_tool_definition",
        "is_hosted_tool_class",
        "is_hosted_tool_definition",
        "judge_agent_evaluation",
        "kimi_formula_toolset",
        "list_installed_skills",
        "load_skill_package",
        "openai_apply_patch_tool",
        "openai_code_interpreter_container",
        "openai_code_interpreter_tool",
        "openai_computer_use_tool",
        "openai_custom_tool",
        "openai_custom_tool_format_grammar",
        "openai_custom_tool_format_text",
        "openai_domain_secret",
        "openai_file_search_filter",
        "openai_file_search_filter_group",
        "openai_file_search_tool",
        "openai_hosted_tool",
        "openai_image_generation_tool",
        "openai_image_mask",
        "openai_inline_skill",
        "openai_inline_skill_source",
        "openai_local_skill",
        "openai_mcp_approval_response",
        "openai_mcp_tool",
        "openai_programmatic_tool_calling_tool",
        "openai_namespace_tool",
        "openai_network_policy_allowlist",
        "openai_network_policy_disabled",
        "openai_response_options",
        "openai_response_reference",
        "openai_skill_reference",
        "openai_tool_search_tool",
        "openai_user_location",
        "openai_web_search_tool",
        "parse_azure_openai_provider_data_part",
        "parse_openai_provider_data_part",
        "parse_ui_message_request",
        "permission_allowlist_approval_policy",
        "prepare_subagents_for_agent",
        "provider_data_part",
        "publish_skill",
        "qwen_code_interpreter_tool",
        "qwen_file_search_tool",
        "qwen_hosted_tool",
        "qwen_image_search_tool",
        "qwen_mcp_tool",
        "qwen_web_extractor_tool",
        "qwen_web_search_image_tool",
        "qwen_web_search_tool",
        "remote_tool",
        "render_provider_support_markdown",
        "run_agent_evaluation",
        "run_agent_evaluation_fixture",
        "run_agent_group",
        "run_skill",
        "run_workflow",
        "serialize_ui_message",
        "serialize_ui_message_chunk",
        "summarize_agent_trace",
        "system",
        "text_part",
        "to_ui_message",
        "to_ui_message_stream",
        "to_ui_messages",
        "tool_call_part",
        "tool_result_part",
        "transcribe_audio",
        "user",
        "validate_skill",
        "validate_workflow_expectations",
        "vertex_code_execution_tool",
        "vertex_computer_use_tool",
        "vertex_external_search_tool",
        "vertex_google_maps_tool",
        "vertex_google_search_tool",
        "vertex_url_context_tool",
        "vertex_vertex_ai_search_tool",
        "workflow_step",
        "wrap_language_model",
    )
)

_CATEGORY_BY_MODULE = {
    "agent": "agent",
    "agent_evaluation": "agent",
    "agent_state": "agent",
    "audio": "foundation",
    "catalog": "catalog",
    "embed": "foundation",
    "errors": "errors",
    "gateway": "gateway",
    "generate_object": "foundation",
    "generate_text": "foundation",
    "grounded_text": "foundation",
    "messages": "messages",
    "middleware": "middleware",
    "observability": "observability",
    "provider_support": "provider-support",
    "providers.anthropic": "provider",
    "providers.azure_openai": "provider",
    "providers.base": "provider",
    "providers.bedrock": "provider",
    "providers.gemini": "provider",
    "providers.kimi": "provider",
    "providers.ollama": "provider",
    "providers.openai": "provider",
    "providers.openrouter": "provider",
    "providers.qwen": "provider",
    "providers.vertex": "provider",
    "providers.vllm": "provider",
    "realtime": "realtime",
    "safety": "safety",
    "skillpacks": "skills",
    "skills": "skills",
    "transport": "transport",
    "types": "types",
    "ui": "ui",
    "workflow": "workflow",
}

_NOTES_BY_EXPORT = {
    "create_bedrock": "native-only provider",
    "create_kimi": "tier-1 provider; native extras remain beta",
    "create_ollama": "compatibility provider",
    "create_openrouter": "native-only provider",
    "create_qwen": "tier-1 provider; native extras remain beta",
    "create_vllm": "tier-1 provider; some capabilities are model/task dependent",
    "openai_local_shell_tool": "local shell execution is experimental and must be isolated by applications",
    "openai_shell_tool": "shell execution is experimental and must be isolated by applications",
    "stream_live_agent": "realtime/live APIs are experimental",
}

_EXPORT_LEVELS: dict[str, ApiStabilityLevel] = {
    **{name: "stable" for name in STABLE_EXPORTS},
    **{name: "beta" for name in BETA_EXPORTS},
    **{name: "experimental" for name in EXPERIMENTAL_EXPORTS},
}


def build_api_stability_manifest(
    export_modules: Mapping[str, str] | None = None,
) -> dict[str, ApiStabilityEntry]:
    resolved_export_modules: Mapping[str, str]
    if export_modules is None:
        from . import _EXPORTS

        resolved_export_modules = _EXPORTS
    else:
        resolved_export_modules = export_modules

    return {
        name: ApiStabilityEntry(
            name=name,
            level=level,
            category=_CATEGORY_BY_MODULE[resolved_export_modules[name]],
            notes=_NOTES_BY_EXPORT.get(name, ""),
        )
        for name, level in sorted(_EXPORT_LEVELS.items())
    }


API_STABILITY = build_api_stability_manifest()


def get_api_stability(name: str) -> ApiStabilityEntry:
    return API_STABILITY[name]
